/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author NITRO 5
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchi = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuMant = new javax.swing.JMenu();
        menuingresoProd = new javax.swing.JMenuItem();
        menuingresoClien = new javax.swing.JMenuItem();
        menuMovi = new javax.swing.JMenu();
        menuingresoFact = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuConsultaProd = new javax.swing.JMenuItem();
        menuConsultaClien = new javax.swing.JMenuItem();
        menuConsultaFact = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuReportesProd = new javax.swing.JMenuItem();
        menuReportesClien = new javax.swing.JMenuItem();
        menuReportesFact = new javax.swing.JMenuItem();
        menuAdmin = new javax.swing.JMenu();
        menuAdminUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpEscritorio.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        menuArchi.setText("Archivo");

        jMenuItem1.setText("Cerrar Sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuArchi.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        menuArchi.add(jMenuItem2);

        jMenuBar1.add(menuArchi);

        menuMant.setText("Mantenimiento");

        menuingresoProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/producto.png"))); // NOI18N
        menuingresoProd.setText("Productos");
        menuingresoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuingresoProdActionPerformed(evt);
            }
        });
        menuMant.add(menuingresoProd);

        menuingresoClien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N
        menuingresoClien.setText("Clientes");
        menuingresoClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuingresoClienActionPerformed(evt);
            }
        });
        menuMant.add(menuingresoClien);

        jMenuBar1.add(menuMant);

        menuMovi.setText("Movimiento");

        menuingresoFact.setText("Facturas");
        menuingresoFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuingresoFactActionPerformed(evt);
            }
        });
        menuMovi.add(menuingresoFact);

        jMenuBar1.add(menuMovi);

        menuConsultas.setText("Consultas");

        menuConsultaProd.setText("C. Productos");
        menuConsultas.add(menuConsultaProd);

        menuConsultaClien.setText("C. Clientes");
        menuConsultaClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaClienActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultaClien);

        menuConsultaFact.setText("C Facturas");
        menuConsultas.add(menuConsultaFact);

        jMenuBar1.add(menuConsultas);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        menuReportes.setText("Reportes");

        menuReportesProd.setText("R. Productos");
        menuReportesProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesProdActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesProd);

        menuReportesClien.setText("R. Clientes");
        menuReportesClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesClienActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesClien);

        menuReportesFact.setText("R. Facturas");
        menuReportesFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesFactActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesFact);

        jMenuBar1.add(menuReportes);

        menuAdmin.setText("Administracion");

        menuAdminUser.setText("Usuarios");
        menuAdmin.add(menuAdminUser);

        jMenuBar1.add(menuAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuConsultaClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaClienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultaClienActionPerformed

    private void menuReportesProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReportesProdActionPerformed

    private void menuReportesFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesFactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReportesFactActionPerformed

    private void menuReportesClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesClienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReportesClienActionPerformed

    private void menuingresoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuingresoProdActionPerformed
        IngresoProductos objProd = new IngresoProductos();
        jdpEscritorio.add(objProd);
        objProd.show();
    }//GEN-LAST:event_menuingresoProdActionPerformed

    private void menuingresoClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuingresoClienActionPerformed
        IngresoClientes objCli = new IngresoClientes();
        jdpEscritorio.add(objCli);
        objCli.show();
    }//GEN-LAST:event_menuingresoClienActionPerformed

    private void menuingresoFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuingresoFactActionPerformed
        Facturas objFac = new Facturas();
        jdpEscritorio.add(objFac);
        objFac.show();
    }//GEN-LAST:event_menuingresoFactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuItem menuAdminUser;
    private javax.swing.JMenu menuArchi;
    private javax.swing.JMenuItem menuConsultaClien;
    private javax.swing.JMenuItem menuConsultaFact;
    private javax.swing.JMenuItem menuConsultaProd;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuMant;
    private javax.swing.JMenu menuMovi;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem menuReportesClien;
    private javax.swing.JMenuItem menuReportesFact;
    private javax.swing.JMenuItem menuReportesProd;
    private javax.swing.JMenuItem menuingresoClien;
    private javax.swing.JMenuItem menuingresoFact;
    private javax.swing.JMenuItem menuingresoProd;
    // End of variables declaration//GEN-END:variables
}
